"""initial

Revision ID: e89c44027bea
Revises: 
Create Date: 2026-06-23 15:43:39.022027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e89c44027bea'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('contact_requests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('from_user_id', sa.Uuid(), nullable=False),
    sa.Column('to_user_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['from_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('from_user_id', 'to_user_id')
    )
    op.create_index('idx_contact_from', 'contact_requests', ['from_user_id'], unique=False)
    op.create_index('idx_contact_to', 'contact_requests', ['to_user_id'], unique=False)
    op.create_table('profile_views',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('viewer_id', sa.Uuid(), nullable=False),
    sa.Column('viewed_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['viewed_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['viewer_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('viewer_id', 'viewed_id')
    )
    op.create_index('idx_views_viewed', 'profile_views', ['viewed_id'], unique=False)
    op.create_index('idx_views_viewer', 'profile_views', ['viewer_id'], unique=False)
    op.create_table('tags',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('snapshot_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('tag_id', sa.Uuid(), nullable=False),
    sa.Column('weight', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'tag_id')
    )
    op.create_index('idx_snapshot_tag', 'snapshot_items', ['tag_id'], unique=False)
    op.create_index('idx_snapshot_user', 'snapshot_items', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_snapshot_user', table_name='snapshot_items')
    op.drop_index('idx_snapshot_tag', table_name='snapshot_items')
    op.drop_table('snapshot_items')
    op.drop_table('tags')
    op.drop_index('idx_views_viewer', table_name='profile_views')
    op.drop_index('idx_views_viewed', table_name='profile_views')
    op.drop_table('profile_views')
    op.drop_index('idx_contact_to', table_name='contact_requests')
    op.drop_index('idx_contact_from', table_name='contact_requests')
    op.drop_table('contact_requests')
    op.drop_table('users')
    # ### end Alembic commands ###
